// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo75jwurs6KTVLo5RbTP3qggbW4OBsLlw',
    appId: '1:1018863295961:web:2c578cf7089eaf8b2f0dc8',
    messagingSenderId: '1018863295961',
    projectId: 'blindness-guardian',
    authDomain: 'blindness-guardian.firebaseapp.com',
    storageBucket: 'blindness-guardian.firebasestorage.app',
    measurementId: 'G-YXWD6BCN8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDcudrEW6xVmmNBOjEloPdP6aVB9EBJIc',
    appId: '1:1018863295961:android:8a37385e1ef5560c2f0dc8',
    messagingSenderId: '1018863295961',
    projectId: 'blindness-guardian',
    databaseURL: 'https://blindness-guardian-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blindness-guardian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7mIYhRpyoVcS1x_cDZW8dt_2v2QRoPhw',
    appId: '1:1018863295961:ios:c39b5fe67463214e2f0dc8',
    messagingSenderId: '1018863295961',
    projectId: 'blindness-guardian',
    databaseURL: 'https://blindness-guardian-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blindness-guardian.firebasestorage.app',
    iosBundleId: 'com.blindnessguardian.blindnessGuardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7mIYhRpyoVcS1x_cDZW8dt_2v2QRoPhw',
    appId: '1:1018863295961:ios:c39b5fe67463214e2f0dc8',
    messagingSenderId: '1018863295961',
    projectId: 'blindness-guardian',
    storageBucket: 'blindness-guardian.firebasestorage.app',
    iosBundleId: 'com.blindnessguardian.blindnessGuardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo75jwurs6KTVLo5RbTP3qggbW4OBsLlw',
    appId: '1:1018863295961:web:5ee5cfd5c42db4372f0dc8',
    messagingSenderId: '1018863295961',
    projectId: 'blindness-guardian',
    authDomain: 'blindness-guardian.firebaseapp.com',
    storageBucket: 'blindness-guardian.firebasestorage.app',
    measurementId: 'G-3W0TWCFQGK',
  );
}
